version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
      day: "saturday"   # Runs the update on the first Saturday of the month
      time: "08:00"     # at 08:00 UTC
    groups:
      taquito:
        patterns:
          - "@taquito/*"
      storybook:
        patterns:
          - "@storybook/*"
      eslint:
        patterns:
          - "eslint-*"
      tanstack:
        patterns:
          - "@tanstack/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
