version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    groups:
      taquito:
        patterns:
          - "@taquito/*"
      storybook:
        patterns:
          - "@storybook/*"
      eslint:
        patterns:
          - "eslint-*"
      tanstack:
        patterns:
          - "@tanstack/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
