schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "19ab95a257833429647fc25765a06a"
documents: "./src/graphql/queries/**/*.graphql"
generates:
  src/graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unkown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
