export { default as AddContactIcon } from "./add-contact-s.svg";
export { default as AlertIcon } from "./alert.svg";
export { default as ArrowDownLeftIcon } from "./arrow-down-left.svg";
export { default as ArrowLeftCircleIcon } from "./arrow-left-circle.svg";
export { default as ArrowUpRightIcon } from "./arrow-up-right.svg";
export { default as BookIcon } from "./book.svg";
export { default as CheckmarkIcon } from "./checkmark.svg";
export { default as ChevronDownIcon } from "./chevron-down.svg";
export { default as ChevronRightIcon } from "./chevron-right.svg";
export { default as CloseIcon } from "./close.svg";
export { default as CodeSandboxIcon } from "./code-sandbox.svg";
export { default as ContactIcon } from "./contact-s.svg";
export { default as ContractIcon } from "./contract.svg";
export { default as CrossedCircleIcon } from "./crossed-circle.svg";
export { default as DelegateIcon } from "./delegate-s.svg";
export { default as DownloadIcon } from "./download.svg";
export { default as EditIcon } from "./edit.svg";
export { default as EnvelopeIcon } from "./envelope.svg";
export { default as ExternalLinkIcon } from "./external-link.svg";
export { default as FA12Icon } from "./fa12.svg";
export { default as FA2Icon } from "./fa2.svg";
export { default as FacebookIcon } from "./facebook.svg";
export { default as FileCopyIcon } from "./file-copy.svg";
export { default as FilterIcon } from "./filter.svg";
export { default as GoogleIcon } from "./google.svg";
export { default as HourglassIcon } from "./hourglass.svg";
export { default as IncomingArrowIcon } from "./incoming-arrow.svg";
export { default as KeyIcon } from "./key.svg";
export { default as LogoDarkIcon } from "./logo-dark.svg";
export { default as LogoLightIcon } from "./logo-light.svg";
export { default as LogoutIcon } from "./logout.svg";
export { default as MailIcon } from "./mail.svg";
export { default as MenuIcon } from "./menu.svg";
export { default as MoonIcon } from "./moon.svg";
export { default as MultisigIcon } from "./multisig.svg";
export { default as OutgoingArrowIcon } from "./outgoing-arrow.svg";
export { default as PlusIcon } from "./plus.svg";
export { default as RedditIcon } from "./reddit.svg";
export { default as SearchIcon } from "./search.svg";
export { default as SelectorIcon } from "./selector.svg";
export { default as SettingsIcon } from "./settings.svg";
export { default as TagIcon } from "./tag.svg";
export { default as ThreeDotsIcon } from "./three-dots.svg";
export { default as TrashIcon } from "./trash.svg";
export { default as TwitterIcon } from "./twitter.svg";
export { default as UnknownIcon } from "./unknown-contact.svg";
export { default as USBIcon } from "./usb.svg";
export { default as UserPlusIcon } from "./user-plus.svg";
export { default as VerifiedIcon } from "./verified.svg";
export { default as WalletIcon } from "./wallet.svg";
export { default as RadioIcon } from "./radio.svg";
export { default as LockIcon } from "./lock.svg";
export { default as AlertCircleIcon } from "./alert-circle.svg";
export { TokenIcon } from "./TokenIcon";

import CloseIcon from "./close.svg";

// This is a temporary icon to replace desktop ones until we migrate components to web
export const StubIcon = CloseIcon;
