export { TokenIcon } from "./TokenIcon";

export { default as AddContactIcon } from "./add-contact-s.svg";
export { default as ArrowDownLeftIcon } from "./arrow-down-left.svg";
export { default as ChevronDownIcon } from "./chevron-down.svg";
export { default as ContactIcon } from "./contact-s.svg";
export { default as DelegateIcon } from "./delegate-s.svg";
export { default as FA12Icon } from "./fa12.svg";
export { default as FA2Icon } from "./fa2.svg";
export { default as FacebookSocialIcon } from "./facebook-social.svg";
export { default as FileCopyIcon } from "./file-copy.svg";
export { default as GoogleSocialIcon } from "./google-social.svg";
export { default as KeyIcon } from "./key.svg";
export { default as LedgerSocial } from "./ledger-social.svg";
export { default as LogoDarkIcon } from "./logo-dark.svg";
export { default as LogoLightIcon } from "./logo-light.svg";
export { default as MailIcon } from "./mail.svg";
export { default as MenuIcon } from "./menu.svg";
export { default as MultisigIcon } from "./multisig.svg";
export { default as PlusIcon } from "./plus.svg";
export { default as RedditSocialIcon } from "./reddit-social.svg";
export { default as UnknownSocialIcon } from "./unknown-social.svg";
export { default as XSocialIcon } from "./x-social.svg";
export { default as VerifiedIcon } from "./verified.svg";
export { default as ArrowLeftCircleIcon } from "./arrow-left-circle.svg";
export { default as CloseIcon } from "./close.svg";
