name: Build

on: push

jobs:
  build_app:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      # this one is for yarn 1.x. It saves its cache in .cache/yarn/v6
      # whilst yarn 2+ would use .cache/yarn
      # They must be aligned so that cache can be used by
      # the setup-node action and our own version of yarn (3.x)
      YARN_CACHE_FOLDER: /home/runner/.cache/yarn

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Setup yarn 3.x
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn --version

      - name: Install packages
        env:
          YARN_CACHE_FOLDER: /home/runner/.cache/yarn/v6
        run: yarn install --immutable

      - name: Check format
        run: npm run format:ci

      - name: Run linter
        run: npm run lint

      - name: Typecheck code
        run: npm run typecheck

      - name: Run tests
        run: CI=true npm run test

      - name: Build
        run: yarn build

      # - name: Upload
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app_dist
      #     path: build
      #     if-no-files-found: error
